# Generated by Django 4.2.4 on 2023-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('ทดสอบ', 'ทดสอบ'), ('รัฐวิสาหกิจ', 'รัฐวิสาหกิจ')], default='1', max_length=20),
        ),
    ]
