# Generated by Django 4.2.4 on 2023-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
